apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: docker.io/opsmx11/dev-petclinic-apple
  newTag: 66-critical
- name: docker.io/opsmx11/dev-petclinic-poc
  newTag: 67-nocritical
